version: "3"

services:
    db:
        image: mariadb
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MARIADB_ROOT_PASSWORD: ayoade
            MARIADB_DATABASE: ayoade
            MARIADB_USER: ayoade
            MARIADB_PASSWORD: ayoade
        ports:
            - 3306:3306
        networks:
            - ayoade
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./../:/var/www/symfony/
        networks:
            - ayoade
    nginx:
        build:
            context: ./nginx
        volumes:
            - ./../:/var/www/symfony/
        ports:
            - 8001:80
        networks:
            - ayoade
        env_file:
            - .env.nginx.local

volumes:
    db_app:

networks:
    ayoade:
